# Generated by Django 5.1 on 2024-08-26 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'корзинн', 'verbose_name_plural': 'Корзины заказов'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'цветок в корзине', 'verbose_name_plural': 'Цветы в корзинах'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'цветок', 'verbose_name_plural': 'Цветы'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.AlterField(
            model_name='cart',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product', verbose_name='Цветок в корзине'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delivery_address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='cart_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость корзины'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Заказан'), ('RECEIVED', 'Получен'), ('CANCELED', 'Отменен'), ('PAID', 'Оплачен')], max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/website/img/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Цветок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
