# Generated by Django 5.1 on 2024-08-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.CharField(max_length=16, verbose_name='ID бота')),
            ],
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='cart_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоит руб.'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Заказан'), ('RECEIVED', 'Получен'), ('CANCELED', 'Отменен'), ('PAID', 'Оплачен')], default='ORDERED', max_length=10, verbose_name='Статус'),
        ),
    ]
